### ISSUE TITLE
内存泄漏和JsonObject引起的崩溃问题

### ISSUE THREAD

**Issue by qqwx1986** [ThinkingDataAnalytics/unreal-sdk#1]
1.内存泄漏问题 FRequestHelper new 了后没有delete

2.多线程下使用 m_PresetPropertiesJsonObject 会有问题，而且使用方法不对，目前使用的move，只能copy，并发下会造成崩溃。
并发发送就能重现

**Comment by BugLiee** [comment]
问题1 会在下个版本修复提交，当前若要使用可以先在FRequestHelper的回调最后一行return修改为delete this

问题2 git最新版本上线前发现了该问题，已经使用FString替代原来的FJsonObject了，您这边可以先同步下最新的git代码
